# Generated by Django 5.0.8 on 2024-08-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Historial', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoTraducido', models.CharField(max_length=100)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('mostrar', models.CharField(max_length=30)),
                ('historial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones_historial', to='Historial.historial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='Usuarios.usuario')),
            ],
            options={
                'db_table': 'Traduccion',
            },
        ),
    ]
