# Generated by Django 5.0.8 on 2024-08-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
        ('Traduccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones_traduccion', to='Sistema.sistema'),
        ),
    ]
