# Generated by Django 5.0.8 on 2024-08-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_remove_sistema_traducciones'),
        ('Traduccion', '0002_traduccion_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduccion',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='Sistema.sistema'),
        ),
    ]
