# Generated by Django 5.0.8 on 2024-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('verificarEstado', models.BooleanField()),
            ],
            options={
                'db_table': 'Camara',
            },
        ),
    ]
