# Generated by Django 5.0.8 on 2024-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Camara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCamara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreConfiguracion', models.CharField(max_length=30)),
                ('configurarCamara', models.CharField(max_length=30)),
                ('camaras', models.ManyToManyField(blank=True, related_name='configuraciones', to='Camara.camara')),
            ],
        ),
    ]
