# Generated by Django 5.0.8 on 2024-08-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camara', '0001_initial'),
        ('ConfiguracionCamara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncamara',
            name='camaras',
        ),
        migrations.AddField(
            model_name='configuracioncamara',
            name='camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='Camara.camara'),
        ),
        migrations.AlterModelTable(
            name='configuracioncamara',
            table='ConfiguracionCamara',
        ),
    ]
