# Generated by Django 5.0.8 on 2024-08-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DiccionarioGestos', '0001_initial'),
        ('Sistema', '0002_remove_sistema_traducciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('diccionarioGestos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestos_diccionario', to='DiccionarioGestos.diccionariogestos')),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestos', to='Sistema.sistema')),
            ],
            options={
                'db_table': 'Gestos',
            },
        ),
    ]
