# Generated by Django 5.0.8 on 2024-08-06 22:35

from django.db import migrations

def add_initial_gestos(apps, schema_editor):
    Gestos = apps.get_model('Gestos', 'Gestos')
    gestos = [
        {'id': 0, 'descripcion': 'A'},
        {'id': 1, 'descripcion': 'B'},
        {'id': 2, 'descripcion': 'C'},
        {'id': 3, 'descripcion': 'D'},
        {'id': 4, 'descripcion': 'E'},
        {'id': 5, 'descripcion': 'F'},
        {'id': 6, 'descripcion': 'G'},
        {'id': 7, 'descripcion': 'H'},
        {'id': 8, 'descripcion': 'I'},
        {'id': 9, 'descripcion': 'J'},
        {'id': 10, 'descripcion': 'K'},
        {'id': 11, 'descripcion': 'L'},
        {'id': 12, 'descripcion': 'M'},
        {'id': 13, 'descripcion': 'N'},
        {'id': 14, 'descripcion': 'O'},
        {'id': 15, 'descripcion': 'P'},
        {'id': 16, 'descripcion': 'Q'},
        {'id': 17, 'descripcion': 'R'},
        {'id': 18, 'descripcion': 'S'},
        {'id': 19, 'descripcion': 'T'},
        {'id': 20, 'descripcion': 'U'},
        {'id': 21, 'descripcion': 'V'},
        {'id': 22, 'descripcion': 'W'},
        {'id': 23, 'descripcion': 'X'},
        {'id': 24, 'descripcion': 'Y'},
        {'id': 25, 'descripcion': 'Z'},
    ]
    for gesto in gestos:
        Gestos.objects.create(**gesto)

class Migration(migrations.Migration):

    dependencies = [
        ('Gestos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_gestos),
    ]
