# Generated by Django 5.0.8 on 2024-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioGestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actualizarDiccionario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'DiccionarioGestos',
            },
        ),
    ]
