# Generated by Django 5.0.8 on 2024-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=60)),
                ('rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
