# Generated by Django 5.0.8 on 2024-08-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Camara', '0001_initial'),
        ('Traduccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('verificarEstado', models.BooleanField()),
                ('camara', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistema', to='Camara.camara')),
                ('traducciones', models.ManyToManyField(blank=True, related_name='sistemas', to='Traduccion.traduccion')),
            ],
            options={
                'db_table': 'Sistema',
            },
        ),
    ]
