# Generated by Django 5.0.8 on 2024-08-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='traducciones',
        ),
    ]
